apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: togglemaster-homolog
resources:
  - ../../base
labels:
  - pairs:
      app.kubernetes.io/environment: homolog
    includeSelectors: true
images:
  - name: togglemaster-evaluation-service
    newName: 935091649608.dkr.ecr.us-east-1.amazonaws.com/togglemaster-homolog/evaluation-service
    newTag: sha-0000000
patches:
  - target:
      kind: ConfigMap
      name: evaluation-service-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: homolog
      - op: replace
        path: /data/REDIS_URL
        value: rediss://master.togglemaster-homolog-redis.e30slj.use1.cache.amazonaws.com:6379
      - op: replace
        path: /data/AWS_SQS_URL
        value: https://sqs.us-east-1.amazonaws.com/935091649608/togglemaster-homolog-evaluation-events
  - target:
      kind: HorizontalPodAutoscaler
      name: evaluation-service
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 3
