apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: togglemaster-homolog
resources:
  - ../../base
labels:
  - pairs:
      app.kubernetes.io/environment: homolog
    includeSelectors: true
images:
  - name: togglemaster-analytics-service
    newName: 000000000000.dkr.ecr.us-east-1.amazonaws.com/togglemaster-homolog/analytics-service
    newTag: sha-0000000
patches:
  - target:
      kind: ConfigMap
      name: analytics-service-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: homolog
      - op: replace
        path: /data/AWS_DYNAMODB_TABLE
        value: ToggleMasterAnalytics-homolog
  - target:
      kind: HorizontalPodAutoscaler
      name: analytics-service
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 3
